# Example  .gitlab-ci.yml file
stages:
  - maventry
  - mavencd
  - androidtry
  - maventest
  - androidtest

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot_tag       # this is LINK to the shell runner on the remote-server
  script:
    - cd Backend/gamedr    #change directory to where you have your springboot application
    - mvn package

maven-deploy:
  stage: mavencd
  tags:
    - SB_CD
  script:
    - cd Backend/gamedr
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    - main

android-build: #this is another job
  image: gjandres/android-ci:latest     		# this is a directive to DOCKER
  stage: androidtry
  tags:
    - AS_1         					#this is LINK to the docker runner on the remote-server
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gamedr/gradlew  			#change directory to where you have ‘gradlew’ in your android directory
  script:
    - cd Frontend/gamedr				#change directory to where you have your android application
    - ./gradlew assemble

maven-test:
  stage: maventest
  tags:
    - maven-test
  script:
    - cd Backend/gamedr
    - mvn test
  artifacts:
    paths:
      - Backend/target.*.jar

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gamedr/gradlew
  tags:
   - AS_test
  script:
    - cd Frontend/gamedr
    - ./gradlew test
